import pandas as pd
df = pd.read_excel('Canada.xlsx', sheet_name='Canada by Citizenship',
                   skiprows=range(20), skipfooter=2)
print(df.info())
print(df.head(4))
print(df.tail(3))
print(df.shape)
print(df.describe())
print(df.columns.values)
print(df.index.values)
df.drop(['AREA', "REG", 'DEV', "Type", "Coverage"], axis=1, inplace=True)
print(df.head(2))
df.rename(columns={'OdName' : 'Country', 'AreaName' : 'Continent', 'RegName' : 'Region'}, inplace=True)
print(df.columns)
df['Total'] = df.sum(axis=1)
print(df.head(2))
temp = df[['Country', 1980, 1981, 1982, 1983, 1984, 1985]]
print(temp.head(5))
print(temp.Country)
print(temp['Country'])
df.set_index('Country', inplace=True)
print(df.head(3))
print(df.index.values)
df.index.name = None
print(df.index.values)
print(df.loc['Japan'])
print(df.iloc[88])
print(df[df.index == 'Japan'].T)
print(df.loc['Japan', 2013])
print(df.loc['Japan', [1980, 1981, 1982, 1983]])
print(df.iloc[90, [3, 4, 5, 6]])
years = list(map(str, range(1980, 2014)))
print(years)
condition = df['Continent'] == 'Asia'
print(condition)
t = df[(df['Continent'] == 'Asia') & (df['Region'] == 'Southern Asia')]
print(t.head(3))
print(t.shape)
print(t.columns)