print("Pham Van Phuong")
name = "Daniel Pham"
print(name)
print(name, len(name))
print(name[0], name[-2])
print(name[3:6])
print(name[-3:-1])
print(name[:2])
print(name[-3:])
print(name[::3])
print(name[1:5:2])
print(3*name)
print(name.upper())
print(name.lower())
name = name.replace('Daniel', "Van Phuong")
print(name)
print(name.find('Pham'))
print(name.find('abc'))