tuples = ('Hello', 1, 3.14, True)
print(tuples)
print(type(tuples))
print(type(tuples[0]))
print(len(tuples))
print(type(tuples[-1]))
print(type(tuples[0]))
print(type(tuples[1]))
print(type(tuples[2]))
print(type(tuples[3]))
tuples2 = tuples + ('add', 'something', 1, 3.4)
print(tuples2)
print(tuples[:2])
print(tuples[3:])
print(tuples[2:4])
#tuples2 = sorted(tuples2)
#print(tuples2)
NestedTuples = (1, 2, 3, ('Hello', 3.4), (3,4,5), 'end')
print(NestedTuples)
print(len(NestedTuples))
print(NestedTuples[3])
print(type(NestedTuples[3]))
print(NestedTuples[3][0])
print(NestedTuples[3][0][1])
