import numpy as np
np_vector = np.array([1, 2, 3])
print(np_vector)
print(type(np_vector))
print(np_vector.shape)
np_matrix = np.array([[1, 2, 3], [3, 4, 5]])
print(np_matrix)
print(type(np_matrix))
print(np_matrix.shape)
np_cube = np.array([
    [[1, 2], [4, 3], [5, 9]],
    [[3, 1], [0, 1], [9, 1]]
])
print(np_cube)
print(type(np_cube))
print(np_cube.shape)
np_vector = np.zeros((5, ))
print(np_vector)
np_vector = np.ones((5, ))
print(np_vector)
np_vector = np.full((5, ), 999)
print(np_vector)
np_vector = np.full((2, 3), 999)
print(np_vector)
np_vector = np.full((2, 3, 2), 999)
print(np_vector)
unit_matrix = np.eye((4))
print(unit_matrix)
arange = np.arange(1, 22, 3)
print(arange)
rand_matrix = np.random.random((2, 3))
print(rand_matrix)